spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talent_information?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  application:
    name: Enterprise talents

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-wait: -1 #连接池最大阻塞等待时间，使用负值表示没有限制
        max-active: 8 #连接池最大连接数
        max-idle: 8 #连接池最大空闲连接数
        min-idle: 0 #连接池最小空闲连接数
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.kgc.bean
  configuration:
    map-underscore-to-camel-case: true



